site_name: prototyp
site_url: "https://a-jandali.github.io/mkdoc-prototyp/"
site_description: "prototyp Mkdoc"
site_author: "Jandali"

repo_name: mkdoc-prototyp
repo_url: https://github.com/a-jandali/mkdoc-prototyp

theme:
  name: material

plugins:
  - search
  - blog
